// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmvbdzzlylfsltwcdfqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtdmJkenpseWxmc2x0d2NkZnFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwOTk3NTAsImV4cCI6MjA2OTY3NTc1MH0.EByinYcdhBei-IqBQSFItZ5FQKZwpNp4w6Jr2oleETw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});